# Generated by Django 4.1.6 on 2023-03-02 09:02

import YourClass.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("YourClass", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="filename",
            field=models.CharField(max_length=64, null=True, verbose_name="첨부파일명"),
        ),
        migrations.AlterField(
            model_name="member",
            name="rdate",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 2, 9, 2, 2, 554555)
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 2, 9, 2, 2, 554555)
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=YourClass.models.get_file_path,
                verbose_name="파일",
            ),
        ),
    ]
